### ISSUE TITLE
DOMException because player didn't interact.

### ISSUE THREAD

**Issue by Ikabodo** [theripper93/Combat-Booster#12] opened 2022-02-03 23:56 UTC
This happens with only Combat Booster active. Not sure if it is a core issue or note.

**Reproduce:**
* Add an animated webm as a turn marker
* Start combat
* Refresh page

If these steps are followed, a black box shows instead of the animated webm.
![image](https://user-images.githubusercontent.com/7766890/152448886-6fbf8cad-3ef0-4cc6-91a7-9845e396855f.png)

The following is showed in the console.
```
core.min.js:8 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
```

**Comment by theripper93** [comment] 2022-02-04 13:31
I cannot reproduce this issue - maybe it's the specific file for some reason. I will nontheless set the video to muted since that could be the problem as chrome does not easly allow autoplay of videos with audio. It will be in the next update - feel free to reopen the issue if it persists

**Closed by theripper93** 2022-02-04 13:31 UTC
